"""Added a few changes

Revision ID: a22fb7b2a63c
Revises: b094b6fe81c4
Create Date: 2024-09-23 16:59:24.446090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22fb7b2a63c'
down_revision: Union[str, None] = 'b094b6fe81c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
